#!/bin/sh

if [[ ! -z "$SSH_SERVER" ]]; then
  echo "$SSH_PUBLIC_KEY" > ~/.ssh/id_rsa.pub
  echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
  chmod 0700 -R ~/.ssh
  ssh -4 -o 'StrictHostKeyChecking no' -f "-L$TUNNEL_PORT:$DB_HOST:$DB_PORT" "$SSH_USER@$SSH_SERVER" -N
fi

